import Head from 'next/head'
import Sidebar from '../components/Sidebar';
// import Footer from '../components/Footer';
import dynamic from 'next/dynamic';
import React from "react";
import { Alert } from '../components/alert.jsx';
// import Trade from '../components/Trade';

const Header = dynamic(() => import('../components/Header'), {
    ssr: false,
})

const Chat = dynamic(() => import('../components/Chat'), {
    ssr: false,
})

export default function Home() {
    return (
        <div className="min-h-screen" data-theme="wireframe">
            <Head>
                <title>ChatSiri</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='relative'>
                <Sidebar />
                <div className='flex justify-center m-auto'>
                    <div className='mt-20'>
                        <Chat />
                    </div>
                </div>
            </div>

            <Alert />


        </div >
    )
}
