import Head from 'next/head'
import Sidebar from '../components/Sidebar';
import React from "react";
import dynamic from 'next/dynamic';
import { Alert } from '../components/alert.jsx';

const Faucet = dynamic(() => import('../components/Faucet'), {
    ssr: false,
})

export default function Fau() {
    return (
        <div className="min-h-screen" data-theme="wireframe">
            <Head>
                <title>Swap</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='relative'>
                <Sidebar />
                <div className='flex justify-center m-auto'>
                    <div className='mt-20 flex flex-col w-96'>

                        <Faucet />

                    </div>
                </div>
            </div>

            <Alert />

        </div >
    )
}
